### ISSUE TITLE
"libnative.so" how do i fix this please

### ISSUE THREAD

**Issue by JohnKinyanjui** [Desdaemon/flutter_rust_bridge_template#10]
I/bridge_templat(13896): Compiler allocated 5171KB to compile void android.view.ViewRootImpl.performTraversals()

════════ Exception caught by widgets library ═══════════════════════════════════
The following ArgumentError was thrown building Builder:
Invalid argument(s): Failed to load dynamic library 'libnative.so': dlopen failed: library "libnative.so" not found

The relevant error-causing widget was
MaterialApp
package:flutter_rust_bridge_template/main.dart:14
When the exception was thrown, this was the stack
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      api
package:flutter_rust_bridge_template/ffi.dart:22

**Comment by Desdaemon** [comment]
Hi, can you give me some more details of what you're doing? A `flutter run --verbose` and `flutter doctor --verbose` should be enough.

**Comment by alanpq** [comment]
Bumping this as I'm getting the same issue, here is the output of `flutter doctor`:
```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale en-IE)
    • Flutter version 3.0.5 at X:\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)     
    • Android SDK at C:\Users\Alan\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)     
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)    

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\Alan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (5 available)
    • Pixel 4 XL (mobile)          • 9B151FFBA002SW   • android-arm64  • Android 12 (API 32)
    • Windows (desktop)            • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)                   • edge             • web-javascript • Microsoft Edge 103.0.1264.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
``` 

and `flutter run`: https://gist.github.com/alanpq/0f8c31750147c4dc942b454ecebaf1fb

**Comment by Desdaemon** [comment]
This is an issue with the build.gradle file as it invokes a possibly non-existent `sh` on Windows. I will fix this soon.
